"""Lab 08.4, step 2: a small precision sweep on the CPU, generated by you (not a validation of the law).

    python labs/module-08/lesson-04/sweep.py                  # free CPU, about 25 minutes
    python labs/module-08/lesson-04/sweep.py --variant gpu --device cuda    # any GPU: wider models, more tokens

Part A — training precision. Toy models at three widths (64, 96, 128 via frontierlab.optim.mup.width_config), each
trained 150 steps x 16 x 128 tokens with weight-only INT-b fake quantisation of every block linear (``--recipe
w-int<b>``: per-row fp32 scale, straight-through gradients; the Eq. 3 setting of arXiv 2411.04330, where only the
weights are trained in low precision), b in {3, 4, 6, 8}, plus the unquantised arm. 15 runs, same seed and data.
Part B — post-training quantisation vs data. The width-128 unquantised model trained for 75, 150, 300 and 600
steps (separate runs, each with its own full cosine schedule), each then rounded to INT4 and INT3 per row.
Every run is evaluated on 256 fixed held-out windows of 128 tokens. Results: runs/m08/l84/<variant>/results.json.
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import m08  # noqa: E402

from frontierlab.model.config import param_counts  # noqa: E402
from frontierlab.optim.mup import width_config  # noqa: E402
from frontierlab.model import PRESETS  # noqa: E402
from frontierlab.precision import QuantSpec, ptq_  # noqa: E402
from frontierlab.precision import train as prec_train  # noqa: E402

VARIANTS = {
    "cpu": {"preset": "toy", "widths": (64, 96, 128), "bits": (3, 4, 6, 8), "steps": 150, "B": 16, "T": 128,
            "ptq_width": 128, "ptq_steps": (75, 150, 300, 600)},
    "gpu": {"preset": "toy", "widths": (128, 256, 384), "bits": (3, 4, 6, 8), "steps": 1000, "B": 32, "T": 256,
            "ptq_width": 256, "ptq_steps": (250, 500, 1000, 2000)},
}


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", choices=sorted(VARIANTS), default="cpu")
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--root", type=Path, default=Path("runs/m08/l84"))
    a = ap.parse_args(argv)
    v = VARIANTS[a.variant]
    root = a.root / a.variant
    common = ["--preset", v["preset"], "--batch", str(v["B"]), "--seq", str(v["T"]), "--device", a.device,
              "--eval-every", "100000", "--eval-windows", "16", "--log-every", "25"]
    vocab = json.loads(Path("labs/common/data/v0/meta.json").read_text())["vocab_size"]
    results = {"variant": a.variant, "tokens_per_step": v["B"] * v["T"], "train": [], "ptq": []}
    for w in v["widths"]:
        N = param_counts(width_config(PRESETS[v["preset"]](vocab_size=vocab), w))["non_embedding"]
        for b in (*v["bits"], None):
            name = f"w{w}-{'bf16' if b is None else f'int{b}'}"
            run = root / name
            m08.run_arm(run, [*common, "--width", str(w), "--ckpt-every", str(v["steps"]),
                              *([] if b is None else ["--recipe", f"w-int{b}"])], v["steps"])
            loss = m08.mean(m08.eval_losses(run, device=a.device))
            results["train"].append({"run": name, "width": w, "N": N, "bits": b, "D": v["steps"] * v["B"] * v["T"], "loss": loss})
            print(f"{name:12s} N={N:>9,d} loss {loss:.4f}")
    w = v["ptq_width"]
    N = param_counts(width_config(PRESETS[v["preset"]](vocab_size=vocab), w))["non_embedding"]
    for steps in v["ptq_steps"]:
        run = root / f"ptq-w{w}-s{steps}"
        m08.run_arm(run, [*common, "--width", str(w), "--ckpt-every", str(steps)], steps)
        base = m08.eval_losses(run, device=a.device)
        row = {"run": run.name, "width": w, "N": N, "steps": steps, "D": steps * v["B"] * v["T"], "loss": m08.mean(base)}
        for b in (4, 3):
            cache = run / f"eval_ptq_int{b}.json"
            if cache.exists():
                ql = json.loads(cache.read_text())
            else:
                m = prec_train.load_model(run / "checkpoint.pt", recipe="bf16", map_location=a.device).to(a.device)
                ptq_(m, QuantSpec(f"int{b}", (1, 0), "fp32"))
                ql = m08.eval_model(m, device=a.device)
                cache.write_text(json.dumps(ql))
            c = m08.compare(ql, base)
            row[f"delta_int{b}"] = c["diff"]
            row[f"delta_int{b}_ci"] = [c["lo"], c["hi"]]
        results["ptq"].append(row)
        print(f"{run.name:16s} D={row['D']:>9,d} loss {row['loss']:.4f}  PTQ int4 {row['delta_int4']:+.4f}  int3 {row['delta_int3']:+.4f}")
    (root / "results.json").write_text(json.dumps(results, indent=1))
    print(f"wrote {root / 'results.json'}")


if __name__ == "__main__":
    main()
